table fact_prices

	column symbol
		dataType: string
		summarizeBy: none

	column date
		dataType: dateTime
		formatString: yyyy-mm-dd
		summarizeBy: none

	column open
		dataType: double
		summarizeBy: none

	column high
		dataType: double
		summarizeBy: none

	column low
		dataType: double
		summarizeBy: none

	column close
		dataType: double
		summarizeBy: none

	column volume
		dataType: int64
		formatString: #,0
		summarizeBy: none

	/// 每标的第一根 bar 为空（无前收可差分）——保持 blank，绝不替 0。
	column daily_return
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		summarizeBy: none

	/// 每标的前 52 周为空（窗口不足）——保持 blank。
	column pct_from_52w_high
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		summarizeBy: none

	/// 直方图分箱（bin 0.005）：Power BI 原生 Group/Bin 是 GUI 态构件，
	/// 计算列版本可入库可 diff，语义等价。
	column ret_bin = ROUND ( fact_prices[daily_return] / 0.005, 0 ) * 0.005
		dataType: double
		formatString: 0.0%;-0.0%;0.0%
		summarizeBy: none

	partition fact_prices = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(ExportFolder & "\fact_prices.csv"), [Delimiter = ",", Columns = 9, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
					Headers = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Typed = Table.TransformColumnTypes(Headers, {{"symbol", type text}, {"date", type date}, {"open", type number}, {"high", type number}, {"low", type number}, {"close", type number}, {"volume", Int64.Type}, {"daily_return", type number}, {"pct_from_52w_high", type number}})
				in
					Typed
